apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: zealot
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTP"
        targetPort: 7341
  healthcheck:
    enabled: true
    image: kind/healthcheck:96d17375510170c5b867b8bd255cd2826dd5468cc185202d67278a3ba1dd6dcb
  horizontalPodAutoscalerSpec:
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            resources:
              requests:
                memory: "1Gi"
                cpu: "1"
  image: kind/challenge:d920ca99afc1ce676b9292a442efbab69dabcac737a55815ff19e6c9d6071ed6
